
const buttons: any[] = [
  "bold",
  "strikethrough",
  "underline",
  "italic",
  "|",
  "align",
  "|",
  "ul",
  "ol",
  "outdent",
  "indent",
  "|",
  "font",
  "fontsize",
  "brush",
  "paragraph",
  "|",
  "image",
  "link",
  "table",
  "|",
  // "hr",
  // "eraser",
  // "copyformat",
  // "|",
  "fullsize",
  // "selectall",
  "print",
  // "|",
  // "source",
];
export const editorConfig: any = {
  readonly: false,
  toolbar: true,
  spellcheck: true,
  language: "en",
  toolbarButtonSize: window?.innerWidth < 600 ? "small" : window?.innerWidth < 900 ? "medium" : "large",
  toolbarAdaptive: true,
  showCharsCounter: true,
  showWordsCounter: true,
  showXPathInStatusbar: false,
  askBeforePasteHTML: true,
  askBeforePasteFromWord: true,
  //defaultActionOnPaste: "insert_clear_html",
  buttons: buttons,
  uploader: {
    insertImageAsBase64URI: true
  },
  // width: 800,
  height: 500
};